# usage: conda env create -p $(pwd)/miniconda/envs/rnaseq --file environment.yaml 
# -p flag should point to your miniconda installation path.

# name of the conda environment
name: rnaseq

#the paths that conda takes a look for packages. 
#avoid using anaconda as we have experienced issues with it
channels:
        - jacek_marzec
        - conda-forge
        - bioconda
        - r
        - plotly
        - defaults

#install following packages in the conda environment
dependencies:
        - r-base=4.0.5
        - libiconv
        - r-tidyverse
        - bioconductor-edger
        - bioconductor-limma
        - bioconductor-glimma
        - bioconductor-edaseq
        - bioconductor-noiseq
        - bioconductor-clusterprofiler
        - bioconductor-pathview
        - bioconductor-kegg.db
        - bioconductor-reactome.db
        - bioconductor-gsva
        - bioconductor-preprocesscore
        - bioconductor-tximport
        - bioconductor-rhdf5
        - bioconductor-complexheatmap
        - bioconductor-sva
        - r-rapportools
        - r-optparse
        - r-openxlsx
        - r-readr
        - r-dplyr
        - r-tidyr
        - r-tibble
        - r-glue
        - r-rlang
        - r-dt
        - r-matrixstats
        - r-knitr
        - r-heatmaply
        - r-plotly
        - plotly-orca
        - r-scales
        - r-rcircos
        - r-upsetr
        - r-ggplot2
        - r-ggforce
        - r-pdftools
        - r-png
        - r-htmltools
        - r-htmlwidgets
        - r-devtools
        - r-truncnorm
        - r-rcolorbrewer
        - r-corrplot
        - r-msigdbr
        - r-rvcheck=0.1.8
        - pandoc
        - libopenblas=0.3.3
        - bioconductor-ensdb.hsapiens.v75
        - bioconductor-ensdb.hsapiens.v86
        - bioconductor-bsgenome.hsapiens.ucsc.hg19
        - bioconductor-bsgenome.hsapiens.ucsc.hg38
        - awscli
