# usage: conda env create -p $(pwd)/miniconda/envs/rnaseq --file environment.yaml 
# -p flag should point to your miniconda installation path.

# name of the conda environment
name: rnaseq

#the paths that conda takes a look for packages. 
#avoid using anaconda as we have experienced issues with it
channels:
        - jacek_marzec
        - conda-forge
        - bioconda
        - r
        - plotly
        - defaults

#install following packages in the conda environment
dependencies:
        - r-base>=3.6.1
        - libiconv
        - r-tidyverse=1.3.1
        - bioconductor-edger=3.28.0
        - bioconductor-limma=3.42.0
        - bioconductor-glimma=1.14.0
        - bioconductor-edaseq=2.20.0
        - bioconductor-noiseq=2.30.0
        - bioconductor-clusterprofiler=3.14.0
        - bioconductor-pathview=1.26.0
        - bioconductor-kegg.db=3.2.3
        - bioconductor-gsva=1.34.0
        - bioconductor-reactome.db=1.70.0 
        - bioconductor-preprocesscore=1.48.0
        - bioconductor-tximport 
        - bioconductor-rhdf5
        - bioconductor-complexheatmap=2.2.0
        - bioconductor-sva=3.34.0
        - r-rapportools=1.0
        - r-optparse=1.7.1
        - r-openxlsx=4.2.5
        - r-readr=2.1.2
        - r-dplyr
        - r-tidyr=1.2.0
        - r-tibble=3.1.6
        - r-glue=1.6.1 
        - r-rlang
        - r-dt=0.20
        - r-matrixstats=0.61.0
        - r-knitr=1.37
        - r-heatmaply=1.3.0
        - r-plotly=4.9.0
        - plotly-orca
        - r-scales=1.1.1
        - r-rcircos=1.2.1
        - r-upsetr=1.4.0 
        - r-ggplot2=3.2.1
        - r-ggforce=0.3.3
        - r-pdftools=3.0.1
        - r-png=0.1-7 
        - r-htmltools=0.5.2
        - r-htmlwidgets=1.5.4
        - r-devtools=2.4.3 
        - r-manhattanly
        - r-msigdbr=7.4.1 
        - r-lares=4.7
        - r-truncnorm=1.0-8 
        - r-rcolorbrewer=1.1-2
        - r-corrplot=0.92
        - pandoc
        - libopenblas=0.3.3
        - bioconductor-ensdb.hsapiens.v75
        - bioconductor-ensdb.hsapiens.v86
        - bioconductor-bsgenome.hsapiens.ucsc.hg19
        - bioconductor-bsgenome.hsapiens.ucsc.hg38
        - awscli

